version: '3.8'

services:
  medix-api:
    # O build buscará o Dockerfile no diretório '.'
    build: .
    container_name: medix_api_container
    # Garante que o contêiner reinicie automaticamente.
    restart: always
    # Mapeia a porta 80 da VM para a porta 8080 do contêiner.
    ports:
      - "80:8080"
